# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 680)
        MainWindow.setMinimumSize(QtCore.QSize(851, 680))
        MainWindow.setMouseTracking(True)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.showspace = QtWidgets.QWidget(self.centralwidget)
        self.showspace.setMinimumSize(QtCore.QSize(500, 580))
        self.showspace.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.showspace.setMouseTracking(True)
        self.showspace.setStyleSheet("")
        self.showspace.setObjectName("showspace")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.showspace)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.showspace)
        self.widget_2.setMinimumSize(QtCore.QSize(480, 50))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.label_image = QtWidgets.QLabel(self.widget_2)
        self.label_image.setGeometry(QtCore.QRect(0, 19, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_image.setFont(font)
        self.label_image.setStyleSheet("background:white;border:1px solid gray")
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.label_data = QtWidgets.QLabel(self.widget_2)
        self.label_data.setGeometry(QtCore.QRect(60, 19, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_data.setFont(font)
        self.label_data.setStyleSheet("background:lightgrey;border:1px solid gray;border-left:none")
        self.label_data.setAlignment(QtCore.Qt.AlignCenter)
        self.label_data.setObjectName("label_data")
        self.gridLayout_2.addWidget(self.widget_2, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.showspace)
        self.scrollArea.setMinimumSize(QtCore.QSize(480, 480))
        self.scrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.scrollArea.setMouseTracking(True)
        self.scrollArea.setStyleSheet("#scrollArea{border:1px solid black}")
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 500, 550))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(500, 550))
        self.scrollAreaWidgetContents.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.scrollAreaWidgetContents.setMouseTracking(True)
        self.scrollAreaWidgetContents.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.scrollAreaWidgetContents.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.map = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.map.setGeometry(QtCore.QRect(0, 0, 1000, 1000))
        self.map.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.map.setMouseTracking(False)
        self.map.setFocusPolicy(QtCore.Qt.NoFocus)
        self.map.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.map.setText("")
        self.map.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.map.setObjectName("map")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.showspace, 1, 0, 1, 1)
        self.workspace = QtWidgets.QFrame(self.centralwidget)
        self.workspace.setMinimumSize(QtCore.QSize(300, 600))
        self.workspace.setMaximumSize(QtCore.QSize(320, 16777215))
        self.workspace.setStyleSheet("")
        self.workspace.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.workspace.setFrameShadow(QtWidgets.QFrame.Raised)
        self.workspace.setObjectName("workspace")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.workspace)
        self.gridLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bottomright = QtWidgets.QWidget(self.workspace)
        self.bottomright.setMinimumSize(QtCore.QSize(280, 300))
        self.bottomright.setStyleSheet("#bottomright{border:1px solid black}")
        self.bottomright.setObjectName("bottomright")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.bottomright)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.bottomright)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.bottomright)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_6.setObjectName("widget_6")
        self.label_4 = QtWidgets.QLabel(self.widget_6)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 61, 16))
        self.label_4.setObjectName("label_4")
        self.input_x = QtWidgets.QLineEdit(self.widget_6)
        self.input_x.setGeometry(QtCore.QRect(10, 20, 113, 31))
        self.input_x.setObjectName("input_x")
        self.input_y = QtWidgets.QLineEdit(self.widget_6)
        self.input_y.setGeometry(QtCore.QRect(150, 20, 121, 31))
        self.input_y.setObjectName("input_y")
        self.gridLayout_5.addWidget(self.widget_6, 1, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.bottomright)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_7.setObjectName("widget_7")
        self.label_5 = QtWidgets.QLabel(self.widget_7)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 61, 16))
        self.label_5.setObjectName("label_5")
        self.input_type = QtWidgets.QLineEdit(self.widget_7)
        self.input_type.setGeometry(QtCore.QRect(10, 20, 261, 31))
        self.input_type.setObjectName("input_type")
        self.gridLayout_5.addWidget(self.widget_7, 2, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.bottomright)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 140))
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget_8)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.input_detail = QtWidgets.QTextEdit(self.widget_8)
        self.input_detail.setObjectName("input_detail")
        self.gridLayout_6.addWidget(self.input_detail, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_8, 3, 0, 1, 1)
        self.widget_9 = QtWidgets.QWidget(self.bottomright)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_9.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_9.setObjectName("widget_9")
        self.save_edit = QtWidgets.QPushButton(self.widget_9)
        self.save_edit.setGeometry(QtCore.QRect(40, 10, 75, 23))
        self.save_edit.setObjectName("save_edit")
        self.clear_edit = QtWidgets.QPushButton(self.widget_9)
        self.clear_edit.setGeometry(QtCore.QRect(160, 10, 75, 23))
        self.clear_edit.setObjectName("clear_edit")
        self.gridLayout_5.addWidget(self.widget_9, 4, 0, 1, 1)
        self.gridLayout_3.addWidget(self.bottomright, 2, 0, 1, 1)
        self.topright = QtWidgets.QWidget(self.workspace)
        self.topright.setMinimumSize(QtCore.QSize(280, 240))
        self.topright.setMaximumSize(QtCore.QSize(16777215, 300))
        self.topright.setStyleSheet("#topright{border:1px solid black;border-bottom:none}")
        self.topright.setObjectName("topright")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.topright)
        self.gridLayout_4.setContentsMargins(-1, 9, -1, 9)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.topright)
        self.label_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.topright)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_5.setObjectName("widget_5")
        self.input_select = QtWidgets.QLineEdit(self.widget_5)
        self.input_select.setGeometry(QtCore.QRect(0, 0, 221, 30))
        self.input_select.setObjectName("input_select")
        self.select = QtWidgets.QPushButton(self.widget_5)
        self.select.setGeometry(QtCore.QRect(220, 0, 61, 31))
        self.select.setObjectName("select")
        self.select.raise_()
        self.input_select.raise_()
        self.gridLayout_4.addWidget(self.widget_5, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.topright)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 2, 0, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.topright)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 118))
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.sawc_select = QtWidgets.QWidget()
        self.sawc_select.setGeometry(QtCore.QRect(0, 0, 300, 120))
        self.sawc_select.setMinimumSize(QtCore.QSize(300, 120))
        self.sawc_select.setObjectName("sawc_select")
        self.scrollArea_2.setWidget(self.sawc_select)
        self.gridLayout_4.addWidget(self.scrollArea_2, 3, 0, 1, 1)
        self.select_opr = QtWidgets.QFrame(self.topright)
        self.select_opr.setMinimumSize(QtCore.QSize(0, 31))
        self.select_opr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.select_opr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.select_opr.setObjectName("select_opr")
        self.first = QtWidgets.QPushButton(self.select_opr)
        self.first.setGeometry(QtCore.QRect(0, 7, 41, 23))
        self.first.setObjectName("first")
        self.last = QtWidgets.QPushButton(self.select_opr)
        self.last.setGeometry(QtCore.QRect(41, 7, 51, 23))
        self.last.setObjectName("last")
        self.next = QtWidgets.QPushButton(self.select_opr)
        self.next.setGeometry(QtCore.QRect(92, 7, 51, 23))
        self.next.setObjectName("next")
        self.end = QtWidgets.QPushButton(self.select_opr)
        self.end.setGeometry(QtCore.QRect(143, 7, 41, 23))
        self.end.setObjectName("end")
        self.edit = QtWidgets.QPushButton(self.select_opr)
        self.edit.setGeometry(QtCore.QRect(184, 7, 41, 23))
        self.edit.setObjectName("edit")
        self.pushButton = QtWidgets.QPushButton(self.select_opr)
        self.pushButton.setGeometry(QtCore.QRect(225, 7, 51, 23))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.select_opr, 4, 0, 1, 1)
        self.gridLayout_3.addWidget(self.topright, 1, 0, 1, 1)
        self.current_user = QtWidgets.QLabel(self.workspace)
        self.current_user.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.current_user.setFont(font)
        self.current_user.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.current_user.setObjectName("current_user")
        self.gridLayout_3.addWidget(self.current_user, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.workspace, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 23))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_user = QtWidgets.QMenu(self.menubar)
        self.menu_user.setObjectName("menu_user")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionupload = QtWidgets.QAction(MainWindow)
        self.actionupload.setObjectName("actionupload")
        self.actiondownload = QtWidgets.QAction(MainWindow)
        self.actiondownload.setObjectName("actiondownload")
        self.actionproject = QtWidgets.QAction(MainWindow)
        self.actionproject.setObjectName("actionproject")
        self.actiondocument = QtWidgets.QAction(MainWindow)
        self.actiondocument.setObjectName("actiondocument")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.actionlogin_in = QtWidgets.QAction(MainWindow)
        self.actionlogin_in.setObjectName("actionlogin_in")
        self.actionlogin_out = QtWidgets.QAction(MainWindow)
        self.actionlogin_out.setObjectName("actionlogin_out")
        self.menu_file.addAction(self.actionupload)
        self.menu_file.addAction(self.actiondownload)
        self.menu_file.addAction(self.actionproject)
        self.menu_user.addAction(self.actionlogin_in)
        self.menu_user.addAction(self.actionlogin_out)
        self.menu_help.addAction(self.actiondocument)
        self.menu_help.addAction(self.action_about)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_user.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "地图质检工具"))
        self.label_image.setText(_translate("MainWindow", "影像"))
        self.label_data.setText(_translate("MainWindow", "数据"))
        self.label_3.setText(_translate("MainWindow", "标注"))
        self.label_4.setText(_translate("MainWindow", "坐标"))
        self.label_5.setText(_translate("MainWindow", "类型"))
        self.label_6.setText(_translate("MainWindow", "详细描述"))
        self.save_edit.setText(_translate("MainWindow", "保存编辑"))
        self.clear_edit.setText(_translate("MainWindow", "放弃编辑"))
        self.label_2.setText(_translate("MainWindow", "查询"))
        self.select.setText(_translate("MainWindow", "搜索"))
        self.label.setText(_translate("MainWindow", "本次共搜索到0条结果！"))
        self.first.setText(_translate("MainWindow", "首条"))
        self.last.setText(_translate("MainWindow", "上一条"))
        self.next.setText(_translate("MainWindow", "下一条"))
        self.end.setText(_translate("MainWindow", "尾条"))
        self.edit.setText(_translate("MainWindow", "编辑"))
        self.pushButton.setText(_translate("MainWindow", "删除"))
        self.current_user.setText(_translate("MainWindow", "当前用户：尚未登录，请先登录"))
        self.menu_file.setTitle(_translate("MainWindow", "文件"))
        self.menu_user.setTitle(_translate("MainWindow", "用户"))
        self.menu_help.setTitle(_translate("MainWindow", "帮助"))
        self.actionupload.setText(_translate("MainWindow", "上传"))
        self.actiondownload.setText(_translate("MainWindow", "下载"))
        self.actionproject.setText(_translate("MainWindow", "项目"))
        self.actiondocument.setText(_translate("MainWindow", "文档"))
        self.action_about.setText(_translate("MainWindow", "关于"))
        self.actionlogin_in.setText(_translate("MainWindow", "登录"))
        self.actionlogin_out.setText(_translate("MainWindow", "注销"))
